matrix:
  include:
    - language: go
      sudo: true

      go:
        - "1.16"

      install:
        - cd $TRAVIS_BUILD_DIR
        - git config --global url."git@github.com:".insteadOf "https://github.com/"

      addons:
        apt:
          update: true

      script:
        - cd $TRAVIS_BUILD_DIR
        - cat /etc/resolv.conf
        - echo "$TRAVIS_BRANCH"@"$TRAVIS_COMMIT"
        - echo $TRAVIS_BUILD_DIR
        - go mod download
        - go install ./...
        - CGO_ENABLED=0 go test -v -coverprofile=coverage.txt $(go list ./...)

      after_success:
        - bash <(curl -s https://codecov.io/bash)
